travis:
  secure:
    BINSTAR_TOKEN: jfkzbvrDA8Vqa7JRfc2JXmsQ0mnSWbgeMD1AD4GzhLOz0yeFwhZRVF/btJ9Y2WSxiUOZE7DN/sVrmb7NsYnMo1ThSTWVm2xMHaQZ37o2V7a5jiq7VBEd9qXNhD4cZzbEditW2iSJDsQhKp1hdzh70OGFBaXquQ9ZF+wTSmzTqio2H1tbCtCzPKJ3qhyhE1OXPwE+q/xXG6pK7DY4RwG+zYpXK4RzOFi6xftiPyqTtfeXIU2pHUkv1Nh+nnApKP6IVuVdNijeKGvurJsarAnF4uhnIds8OGSZz2e9/QqRxYXz0PCYpauQv/2JDtvIDJmmGj4v6DwdcZ2a1B9Rv0uuIPe0kTbCR1+ZHGRIoHugn3YG25Ylg99vLlQIPVtjkBWdTJ8okjUBC7Br0KixHabo8obZxvVzqgiA2AeQGMEG1Kcbo9MexEBKLRY5gi2CZHIbbKdX54CTPCP/d++BFUYOf95sBZQhtwmZjQGk7Fg1kOi2hCN610BarhWBHtNDnTnb79wI+yUJrqVdkaJRCnjh9HxCpWAkBC/58h9Y4Lde43RmoWiPrQZS8lrSbkZy0kMNh8GOcywD4COIDHuNiUzI01bz70rjLoISgvRBCFfNsi5XsYf+L780eRslQuZaW/NLiWEG/4ZEWnnxs9E6+BQmS0fMgKLQzSCEip8mlug0GbY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
